Art-shop/Art-shop/Models/Artist.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artist()
        {
            this.Artworks = new HashSet<Artwork>();
            this.Auctions = new HashSet<Auction>();
        }
    
        public int ArtistID { get; set; }
        public string ArtistName { get; set; }
        public string Bio { get; set; }
        public string Website { get; set; }
        public string Country { get; set; }
        public string ArtistImageTemp { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Category Category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artwork> Artworks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auction> Auctions { get; set; }
    }
}

Art-shop/Art-shop/Models/Auction.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auction()
        {
            this.Bids = new HashSet<Bid>();
        }
    
        public int AuctionID { get; set; }
        public int ArtworkID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal StartingBid { get; set; }
        public Nullable<decimal> CurrentBid { get; set; }
        public Nullable<int> ArtistID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Artwork Artwork { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bid> Bids { get; set; }
        public virtual user_info user_info { get; set; }
    }
}

Art-shop/Art-shop/Controllers/ArtistsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Art_shop.Models;

namespace Art_shop.Controllers
{
    public class ArtistsController : Controller
    {
        private GalleryEntities db = new GalleryEntities();

        // GET: Artists
        public ActionResult Index()
        {
            return View(db.Artists.ToList());
        }

        // GET: Artists/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist artist = db.Artists.Find(id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            return View(artist);
        }

        // GET: Artists/Create
        public ActionResult Create()
        {
            ViewBag.CategoryList = new SelectList(db.Categories, "CategoryID", "CategoryName");
            return View();
        }

        // POST: Artists/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Artist artist, HttpPostedFileBase ArtistImageFile)
        {
            if (ModelState.IsValid)
            {
                // Check if the file was uploaded
                if (ArtistImageFile != null && ArtistImageFile.ContentLength > 0)
                {
                    // Specify the folder path
                    string folderPath = Server.MapPath("~/Images");

                    // Create the folder if it doesn't exist
                    if (!Directory.Exists(folderPath))
                    {
                        Directory.CreateDirectory(folderPath);
                    }

                    // Get the file name and combine it with the folder path
                    string fileName = Path.GetFileName(ArtistImageFile.FileName);
                    string filePath = Path.Combine(folderPath, fileName);

                    // Save the file to the server
                    ArtistImageFile.SaveAs(filePath);

                    // Set the ArtistImageTemp property to the file name
                    artist.ArtistImageTemp = fileName;

                    // Add the artist to the database
                    db.Artists.Add(artist);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
            }

            // If the model state is not valid or the file was not uploaded,
            // repopulate the CategoryList before returning to the view
            ViewBag.CategoryList = new SelectList(db.Categories, "CategoryID", "CategoryName");
            return View(artist);
        }

        // POST: Artists/CreateWithModel
        [HttpPost]
        [ActionName("CreateWithModel")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Artist artist)
        {
            if (ModelState.IsValid)
            {
                db.Artists.Add(artist);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            // If the model state is not valid, repopulate the CategoryList before returning to the view
            ViewBag.CategoryList = new SelectList(db.Categories, "CategoryID", "CategoryName", artist.CategoryID);
            return View(artist);
        }

        // GET: Artists/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Artist artist = db.Artists.Find(id);
            if (artist == null)
            {
                return HttpNotFound();
            }

            // Assuming you have a method to get categories from your database
            ViewBag.CategoryList = new SelectList(db.Categories, "CategoryID", "CategoryName", artist.CategoryID);

            return View(artist);
        }

        // POST: Artists/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ArtistID,ArtistName,Bio,Website,Country,ArtistImageTemp,CategoryID")] Artist artist)
        {
            if (ModelState.IsValid)
            {
                // Update the state of the entity to Modified
                db.Entry(artist).State = EntityState.Modified;

                // If the CategoryID is not explicitly included in the form, set it from the original artist
                if (artist.CategoryID == 0)
                {
                    artist.CategoryID = db.Artists.Find(artist.ArtistID).CategoryID;
                }

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            // Assuming you have a method to get categories from your database
            ViewBag.CategoryList = new SelectList(db.Categories, "CategoryID", "CategoryName", artist.CategoryID);

            return View(artist);
        }

        // GET: Artists/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist artist = db.Artists.Find(id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            return View(artist);
        }

        // POST: Artists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Artist artist = db.Artists.Find(id);
            db.Artists.Remove(artist);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Art-shop/Art-shop/Controllers/ArtworkController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Art_shop.Models;

namespace Art_shop.Controllers
{
    public class ArtworkController : Controller
    {
        private GalleryEntities db = new GalleryEntities();

        // GET: Artwork
        public ActionResult Index()
        {
            var artworks = db.Artworks.Include(a => a.Category).Include(a => a.Artist);
            return View(artworks.ToList());
        }

        // GET: Artwork/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artwork artwork = db.Artworks.Find(id);
            if (artwork == null)
            {
                return HttpNotFound();
            }
            return View(artwork);
        }

        // GET: Artwork/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName");
            ViewBag.ArtistID = new SelectList(db.Artists, "ArtistID", "ArtistName");
            return View();
        }

        // POST: Artwork/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ArtworkID,ArtworkTitle,Description,Price,CategoryID,ArtistID")] Artwork artwork, HttpPostedFileBase ArtworkImageFile)
        {
            if (ModelState.IsValid)
            {
                if (ArtworkImageFile != null && ArtworkImageFile.ContentLength > 0)
                {
                    // Specify the folder path where you want to save the images
                    string folderPath = Server.MapPath("~/Images/Artworks");

                    if (!Directory.Exists(folderPath))
                    {
                        Directory.CreateDirectory(folderPath);
                    }

                    // Get the file name and combine it with the folder path
                    string fileName = Path.GetFileName(ArtworkImageFile.FileName);
                    string filePath = Path.Combine(folderPath, fileName);

                    // Save the file to the server
                    ArtworkImageFile.SaveAs(filePath);

                    // Set the ArtworkImage property to the file name
                    artwork.ArtworkImage = fileName;
                }

                db.Artworks.Add(artwork);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", artwork.CategoryID);
            ViewBag.ArtistID = new SelectList(db.Artists, "ArtistID", "ArtistName", artwork.ArtistID);
            return View(artwork);
        }

        // GET: Artwork/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artwork artwork = db.Artworks.Find(id);
            if (artwork == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", artwork.CategoryID);
            ViewBag.ArtistID = new SelectList(db.Artists, "ArtistID", "ArtistName", artwork.ArtistID);
            return View(artwork);
        }

        // POST: Artwork/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ArtworkID,ArtworkTitle,Description,Price,CategoryID,ArtistID,ArtworkImage")] Artwork artwork)
        {
            if (ModelState.IsValid)
            {
                db.Entry(artwork).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", artwork.CategoryID);
            ViewBag.ArtistID = new SelectList(db.Artists, "ArtistID", "ArtistName", artwork.ArtistID);
            return View(artwork);
        }

        // GET: Artwork/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artwork artwork = db.Artworks.Find(id);
            if (artwork == null)
            {
                return HttpNotFound();
            }
            return View(artwork);
        }

        // POST: Artwork/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Artwork artwork = db.Artworks.Find(id);
            db.Artworks.Remove(artwork);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        

    }
}

Art-shop/Art-shop/Controllers/user_infoController.cs
 using System.Linq;
using System.Web.Mvc;
using Art_shop.Models;

namespace Art_shop.Controllers
{
    public class user_infoController : Controller
    {
        private GalleryEntities db = new GalleryEntities();

        // Existing actions...

        // GET: user_info/Signup
        public ActionResult Signup()
        {
            return View();
        }

        // POST: user_info/Signup
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Signup([Bind(Include = "first_name,last_name,email,password,mobile,address1,address2")] user_info user_info)
        {
            if (ModelState.IsValid)
            {
                // Perform additional validation as needed
                // For simplicity, the password is stored as plain text in this example
                db.user_info.Add(user_info);
                db.SaveChanges();
                return RedirectToAction("Login");
            }

            return View(user_info);
        }

        // GET: user_info/Login
        public ActionResult Login()
        {
            return View();
        }

        // POST: user_info/Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string email, string password)
        {
            var user = db.user_info.SingleOrDefault(u => u.email == email && u.password == password);

            if (user != null)
            {
                // Store user ID in session for authentication
                Session["UserId"] = user.user_id;
                return RedirectToAction("Dashboard");
            }

            ModelState.AddModelError("", "Invalid email or password");
            return View();
        }

        // GET: user_info/Dashboard
        public ActionResult Dashboard()
        {
            // Check if user is authenticated
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login");
            }

            // Retrieve user data based on the user ID
            int userId = (int)Session["UserId"];
            var user = db.user_info.Find(userId);

            if (user == null)
            {
                // If user not found, redirect to login
                return RedirectToAction("Login");
            }

            // Pass the user data to the view
            return View(user);
        }

        // GET: user_info/Logout
        public ActionResult Logout()
        {
            // Clear user session
            Session.Clear();
            return RedirectToAction("Login");
        }

        public ActionResult Auctions()
        {
            return View();
        }
    }
}

Art-shop/Art-shop/Views/Home/AddtoCart.cshtml
@model Art_shop.Models.Artwork

@{
    Layout = "~/Views/Shared/_LayoutPage_main.cshtml";
}

<br />
<br />
<br />
<br />
<br />
<br />

@using (Html.BeginForm())
{
    <section id="center" class="center_o bg_gray pt-2 pb-2">
        <div class="container-xl">
            <div class="row center_o1">
                <div class="col-md-5">
                    <div class="center_o1l">
                        <h2 class="mb-0"> Cart</h2>
                    </div>
                </div>
                <div class="col-md-7">
                    <div class="center_o1r text-end">
                        <h6 class="mb-0"><a href="#">Home</a> <span class="me-2 ms-2"><i class="fa fa-caret-right"></i></span> Shopping Cart</h6>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="cart_page" class="cart pt-4 pb-4">
        <div class="container-xl">
            <div class="cart_2 row">
                <div class="col-md-6">
                    <h5>MY CART</h5>
                </div>
                <div class="col-md-6">
                    <h5 class="text-end text-uppercase"><a href="#">Continue Shopping</a></h5>
                </div>
            </div>
            <div class="cart_3 row mt-3">
                <div class="col-md-8">
                    <div class="cart_3l">
                        <h6>PRODUCT</h6>
                    </div>
                    <div class="cart_3l1 mt-3 row ms-0 me-0">
                        <div class="col-md-3 ps-0 col-3">
                            <div class="cart_3l1i">
                                @if (!string.IsNullOrEmpty(Model.ArtworkImage))
                                {
                                    <a href="detail.html">
                                        <img src="data:image/jpeg;base64,
                                            @Convert.ToBase64String(System.IO.File.ReadAllBytes(Server.MapPath("~/Images/" + Model.ArtworkImage)))" class="w-100" alt="abc">
                                    </a>
                                }
                            </div>
                        </div>
                        <div class="col-md-9 col-9">
                            <div class="cart_3l1i1">
                                <h6 class="fw-bold">
                                    ArtworkTitle<br />
                                    <span>@Model.ArtworkTitle</span>
                                </h6>
                                <h5 class="col_pink mt-3">@Model.Price</h5>
                                <h6 class="font_12 mt-3 mb-3">@Model.Quantity</h6>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="cart_3r">
                        <h6 class="head_1">SUBTOTAL</h6>
                        <h5 class="text-center col_pink mt-3">@Model.Price</h5>
                        <hr>
                        <h6 class="col_pink mt-3">
                            <a class="button" href="@Url.Action("Checkout", "Home")">PROCEED TO CHECKOUT</a>
                        </h6>
                        <br>
                        <hr>
                    </div>
                </div>
            </div>
        </div>
    </section>
}

Art-shop/Art-shop/Views/Home/Artists.cshtml
@model List<Art_shop.Models.Artist>

@{
    ViewBag.Title = "Artists";
    Layout = "~/Views/Shared/_LayoutPage_main.cshtml";
}
<br />
<br />
<br />
<br />
<section id="center" class="center_o bg_gray pt-2 pb-2">
    <div class="container-xl">
        <div class="row center_o1">
            <div class="col-md-5">
                <div class="center_o1l">
                    <h2 class="mb-0">Artists Detail</h2>
                </div>
            </div>
            <div class="col-md-7">
                <div class="center_o1r text-end">
                    <h6 class="mb-0"><a href="@Url.Action("Index", "Home")">Home</a> <span class="me-2 ms-2"><i class="fa fa-caret-right"></i></span>  Artists</h6>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="row port_1 text-center">
    <div class="col-md-12">
        <h1 class="font_60">Our Artists</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do</p>
        <span class="icon_line col_pink"><i class="fa fa-square-o"></i></span>
    </div>
</div>


<div class="row">
    <section id="detail" class="p_4">
        <div class="container-xl">
            <div class="row detail_1">
                @foreach (var artist in Model)
                {
                    <div class="col-md-4 mb-4">
                        <div class="card">
                            @if (!string.IsNullOrEmpty(artist.ArtistImageTemp))
                            {
                                var imagePath = Server.MapPath("~/Images/" + artist.ArtistImageTemp);
                                var imageBytes = System.IO.File.ReadAllBytes(imagePath);
                                var base64String = Convert.ToBase64String(imageBytes);

                                <img src="data:image/jpeg;base64,@base64String" class="card-img-top" alt="Artist Image" style=" height: 200px;">
                            }

                            <div class="card-body text-dark">
                                <!-- Add text-dark class for dark text color -->
                                <h5 class="card-title">@artist.ArtistName</h5>
                                <p class="card-text text-dark"><strong>Web:</strong> @artist.Website</p>
                                <p class="card-text text-dark"><strong>Country:</strong> @artist.Country</p>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </section>
</div>

<div class="row detail_4 mt-4">
    <h4 class="mb-0">RELATED PRODUCTS</h4>
</div>
<div class="row product_2">
    <!-- Your related product cards here -->
</div>

Art-shop/Art-shop/Views/Home/Auctions.cshtml
@model List<Art_shop.Models.Auction>

@{
    ViewBag.Title = "Auctions";
    Layout = "~/Views/Shared/_LayoutPage_main.cshtml";
}
<br />
<br />
<br />
<div class="container">
    <div class="row port_1 text-center">
        <div class="col-md-12">
            <h1 class="font_60">Auctions</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do</p>
            <span class="icon_line col_pink"><i class="fa fa-square-o"></i></span>
        </div>
    </div>


    <div class="row">
        <div class="col-md-4">
            <!-- Your existing content for the left side (image) -->
            @foreach (var auction in Model)
            {
                <div class="card mb-4">
                    <img src="@Url.Content("~/Images/" + auction.Artwork.ArtworkImage)" class="card-img-top" alt="Artwork Image">
                </div>
            }
        </div>
        <div class="col-md-8">
            <!-- Your existing content for the right side (details, bid options) -->
            @foreach (var auction in Model)
            {
                <div class="card mb-4">
                    <div class="card-body bg-black">
                        <h5 class="card-title">@auction.Artwork.ArtworkTitle</h5>
                        <p class="card-text">Artist: @(auction.Artist != null ? auction.Artist.ArtistName : "N/A")</p>
                        <p class="card-text">Starting Bid: @auction.StartingBid</p>

                        <p class="card-text">Start Date: @auction.StartDate</p>
                        <p class="card-text">End Date: @auction.EndDate</p>

                        @if (User.Identity.IsAuthenticated)
                        {
                            <!-- Display bid options only if the user is logged in -->
                            <select name="bidAmount" id="bidAmount" class="form-control">
                                <option value="100">$100</option>
                                <option value="200">$200</option>
                                <!-- Add more bid options as needed -->
                            </select>
                        }
                        else
                        {
                            <p class="card-text">
                                Log in to place a bid.<br /><br />
                                <a href="@Url.Action("Login", "user_info")" class="btn btn-danger">Login</a>
                            </p>

                        }
                    </div>
                </div>
            }
        </div>
    </div>
</div>


<section id="bloh_h" class="p_4">
    <div class="container-fluid">
        <div class="row port_1 text-center mb-4">
         </div>
          <div class="row bloh_h1">
            <div class="col-md-6 p-0">
                <div class="bloh_h1l">
                    <div id="carouselExampleCaptions3" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src="~/Art_Images/pexels-jean-van-der-meulen-1547708.jpg" class="d-block w-100" alt="...">
                            </div>
                            <div class="carousel-item">
                                <img src="~/Art_Images/pexels-scott-webb-1022934.jpg" class="d-block w-100" alt="...">
                            </div>
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions3" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions3" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="bloh_h1r text-center">
                    <h1 class="font_50">Future Auctions</h1>
                    <p class="mt-3"><span class="fw-bold">Best Artwork</span>, technique in which pigments are mixed with hot, liquid wax. After all of the colours have been applied to the painting surface, a heating element is passed over them until the individual brush or spatula marks fuse into a uniform film.</p>
                    <h6 class="mt-4 mb-0"><a class="button" href="@Url.Action("MemberArtwork", "Home")"><i class="fa fa-bullhorn bg-white col_pink p-3"> </i> <span class="ps-3 pe-3">VIEW GALLERY</span></a></h6>
                </div>
            </div>
        </div>
     </div>
</section>
 

Art-shop/Art-shop/Views/Home/Categories.cshtml
@model Art_shop.Models.Category

@{
    ViewBag.Title = "Categories";
    Layout = "~/Views/Shared/_LayoutPage_main.cshtml";
}

<h2>Categories</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Art-shop/Art-shop/Views/Home/CategoryList.cshtml
@model List<Art_shop.Models.Category>

<ul>
    @foreach (var category in Model)
    {
        <li><a href="@Url.Action("ArtworkByCategory", "Home", new { categoryId = category.CategoryID })">@category.CategoryName</a></li>
    }
</ul>

Art-shop/Art-shop/Views/Home/Shows.cshtml
@model List<Art_shop.Models.Show>

@{
    ViewBag.Title = "Shows";
    Layout = "~/Views/Shared/_LayoutPage_main.cshtml";
}
<br />
<br />
<br />
<br />
<br />
<div class="container">
     <div class="section-title">
        <h2>Exhibition</h2>
        <h3>Explore Our <span>Art Exhibition</span></h3>
        <p>Discover unique art exhibitions.</p>
    </div>

    <div class="row">
        @foreach (var show in Model)
        {
            <div class="col-md-4">
                <div class="card mb-4">
                    <img src="@Url.Content("~/Images/" + show.Show_Image)" class="card-img-top" alt="Show Image">
                </div>
            </div>
            <div class="col-md-8">
                <div class="card mb-4" style="color: black;">
                    <div class="card-body">

                        <h5 class="card-title">@show.Title</h5>
                        <p class="card-text text-dark">Details: @show.Description</p>
                        <p class="card-text text-dark">Show Venue: @show.Venue</p>
                        <p class="card-text text-dark">Organized by: @show.Organizer</p>
                        <h5 class="card-title text-dark">Start Date: @show.StartDate</h5>
                        <h5 class="card-title text-dark">End Date: @show.EndDate</h5>

                    </div>
                </div>
            </div>

        }
    </div>
</div>

Art-shop/Art-shop/Views/Home/User_panel.cshtml
@{
    ViewBag.Title = "User_panel";
    Layout = "~/Views/Shared/_LayoutPage_main.cshtml";
}

<h2>User_panel</h2>